services:
    serve:
        build: .
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=db:5432
        command: ["serve"]
        depends_on:
            - db
        ports:
            - 8001:80
        networks:
          - netdb
        restart: always
    db:
        image: pgvector/pgvector:pg16
        env_file:
            - .env
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
          - netdb

networks:
  netdb:
