[project]
name = "clapclap"
version = "0.1.0"
description = "A CLAP CLI for navidrome"
readme = "README.md"
requires-python = ">=3.13"
maintainers = [
  {name = "TheRaphael0000", email = "me@theraphael0000.ch"}
]
dependencies = [
    "fastapi[standard]>=0.136.3",
    "pgvector>=0.4.2",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.50",
    "opendht>=4.0.0",
    "numpy>=2.5.1",
    "filetype>=1.2.0",
    "tinytag>=2.3.0",
    "faiss-cpu>=1.15.0",
    "uvicorn>=0.52.0",
    "u-msgpack-python>=2.8.0",
    "python-decouple>=3.8",
    "scipy>=1.18.1",
]

[project.optional-dependencies]
full = [
    "transformers>=5.14.1",
    "torch>=2.13.0",
    "torchcodec>=0.15.0",
    "torchaudio>=2.11.0",
]

[project.scripts]
clapclap = "clapclap.cli:main"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/clapclap"]
