# hand-made list, can probably be improved
macro_genres = [
    'ambient',
    'blues',
    'classical',
    'country',
    'edm',
    'pop',
    'electronic',
    'experimental',
    'folk',
    'funk',
    'heavy metal',
    'hip-hop rap',
    'latin tropical',
    'lo-fi',
    'punk',
    'r&b soul',
    'reggae',
    'rock&roll',
    'jazz',
    'traditional',
    'soundtracks',
]