# hand-made list, can probably be improved
macro_genres = [
    'pop',
    'rock',
    'hip-hop',
    'r&b',
    'soul',
    'country',
    'electronic',
    'edm',
    'funk',
    'heavy metal',
    'punk',
    'jazz',
    'blues',
    'folk',
    'reggae',
    'tropical',
    'classical',
    'traditional',
    'ambient',
    'soundtracks',
    'lo-fi',
    'experimental',
]